name: medsam
channels:
  - pytorch
  - nvidia
  - nvidia/label/cuda-11.7.0
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - cuda-cccl=11.7.58
  - cuda-command-line-tools=11.7.0
  - cuda-compiler=11.7.0
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.7.60
  - cuda-cuobjdump=11.7.50
  - cuda-cupti=11.8.87
  - cuda-cuxxfilt=11.7.50
  - cuda-documentation=11.7.50
  - cuda-driver-dev=11.7.60
  - cuda-gdb=11.7.50
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.7.0
  - cuda-memcheck=11.7.50
  - cuda-nsight=11.7.50
  - cuda-nsight-compute=11.7.0
  - cuda-nvcc=11.7.64
  - cuda-nvdisasm=11.7.50
  - cuda-nvml-dev=11.7.50
  - cuda-nvprof=11.7.50
  - cuda-nvprune=11.7.50
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.7.50
  - cuda-nvtx=11.8.86
  - cuda-nvvp=11.7.50
  - cuda-runtime=11.8.0
  - cuda-sanitizer-api=11.7.50
  - cuda-toolkit=11.7.0
  - cuda-tools=11.7.0
  - cuda-version=11.7
  - cuda-visual-tools=11.7.0
  - cudatoolkit=11.7.0
  - ffmpeg=4.3
  - freetype=2.12.1
  - gds-tools=1.3.0.44
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.10.1.25
  - libcufft=10.9.0.58
  - libcufft-dev=10.7.2.50
  - libcufile=1.9.1.3
  - libcufile-dev=1.3.0.44
  - libcurand=10.3.5.147
  - libcurand-dev=10.2.10.50
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.3.5.50
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.3.50
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnpp=11.8.0.86
  - libnpp-dev=11.7.3.21
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.7.2.34
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.2.1
  - nsight-compute=2022.2.0.13
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.16
  - pillow=10.4.0
  - pysocks=1.7.1
  - python=3.10.14
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - readline=8.2
  - sqlite=3.45.3
  - sympy=1.13.2
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.0.2
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - albucore==0.0.17
      - albumentations==1.4.18
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.6.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - argparse==1.4.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==24.2.0
      - babel==2.16.0
      - batchgenerators==0.25.1
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - brotli==1.1.0
      - cffi==1.17.1
      - click==8.1.8
      - colorama==0.4.6
      - comm==0.2.2
      - conda-pack==0.8.1
      - connected-components-3d==3.18.0
      - contourpy==1.3.0
      - crcmod==1.7
      - cryptography==44.0.2
      - cycler==0.12.1
      - debugpy==1.8.5
      - decorator==5.1.1
      - defusedxml==0.7.1
      - easydict==1.13
      - einops==0.8.0
      - eval-type-backport==0.2.0
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastgeodis==1.0.5
      - fastjsonschema==2.20.0
      - feather-format==0.4.1
      - filelock==3.14.0
      - fonttools==4.53.1
      - fqdn==1.5.1
      - future==1.0.0
      - grpcio==1.76.0
      - h11==0.14.0
      - h5py==3.13.0
      - hausdorff==0.2.6
      - httpcore==1.0.5
      - httpx==0.27.2
      - hydra-core==1.3.2
      - imageio==2.35.1
      - inflate64==1.0.1
      - ipykernel==6.29.5
      - ipympl==0.9.4
      - ipython==8.27.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jedi==0.19.1
      - jmespath==0.10.0
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - kornia==0.8.0
      - kornia-rs==0.1.8
      - lazy-loader==0.4
      - linecache2==1.0.0
      - llvmlite==0.44.0
      - markdown==3.8
      - markdown-it-py==3.0.0
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - medpy==0.5.2
      - mistune==3.0.2
      - mmcv==2.2.0
      - mmengine==0.10.7
      - model-index==0.1.11
      - monai==1.3.2
      - multivolumefile==0.2.3
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - nibabel==5.2.1
      - notebook-shim==0.2.4
      - numba==0.61.0
      - numpy==1.26.4
      - omegaconf==2.3.0
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.10.0.84
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - oss2==2.17.0
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pip==25.0.1
      - platformdirs==4.3.6
      - prometheus-client==0.21.0
      - prompt-toolkit==3.0.47
      - protobuf==6.33.1
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py7zr==0.22.0
      - pyarrow==19.0.1
      - pybcj==1.0.3
      - pycox==0.3.0
      - pycparser==2.22
      - pycryptodome==3.22.0
      - pycryptodomex==3.22.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pygments==2.18.0
      - pyparsing==3.1.4
      - pyppmd==1.1.1
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.15
      - pyqt5-sip==12.15.0
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pytz==2023.4
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - pyzstd==0.16.2
      - referencing==0.35.1
      - requests==2.28.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.4.2
      - rpds-py==0.20.0
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.14.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - setuptools==60.2.0
      - simpleitk==2.4.0
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.0.1
      - terminado==0.18.1
      - texttable==1.7.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.6.0
      - tifffile==2024.9.20
      - tinycss2==1.3.0
      - tomli==2.0.1
      - torchtuples==0.2.2
      - tornado==6.4.1
      - tqdm==4.65.2
      - traceback2==1.4.0
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20240906
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - unittest2==1.1.0
      - uri-template==1.3.0
      - urllib3==1.26.20
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.4
      - wheel==0.45.1
      - widgetsnbextension==4.0.13
      - yapf==0.43.0
prefix: /usr/local/anaconda3/envs/medsam
